
spring:
  application:
    name: "Control Work"

  jpa:
    hibernate:
      ddl-auto: validate
  mvc:
    static-path-pattern: /static/**
  freemarker:
    expose-session-attributes: true

  datasource:
    url: jdbc:h2:./db/test;AUTO_SERVER=TRUE
    username: Ahmatbek
    password: qwerty
    driver-class-name: org.h2.Driver
    #  sql:
    #    init:
    #      mode: always
    #============ Mail config
  liquibase:
    change-log: classpath:/db/changelog/master.yml
  mail:
    host: smtp.gmail.com
    username: zhanybek20065732@gmail.com
    password: xmqh zdnf kjld qdkh
    port: 587
    properties:
      mail:
        smtp:
          auth:
            true
          starttls:
            enable: true

  #============ Google config
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 966149106873-7lo5tn780ctd5igelsie5l6lnddkns0k.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile


logging:
  level:
    root: info
    org:
      springframework:
        security: debug
  file:
    path: logs
